Refactor scripts/release

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 run_checks() {
   # Check if a version argument is provided
@@ -26,13 +26,51 @@ run_checks() {
   fi
 }
 
+get_current_version() {
+  grep '^version = ' "$PYPROJECT_FILE" | sed -E 's/version = "(.*)"/\1/'
+}
+
+# Usage: NEW_VERSION=$(increment_version "<current_version>" "<version_type>")
+increment_version() {
+  local version=$1
+  local type=$2
+
+  IFS='.' read -r -a parts <<<"$version"
+  major=${parts[0]}
+  minor=${parts[1]}
+  patch=${parts[2]}
+
+  case "$type" in
+  major)
+    ((major += 1))
+    minor=0
+    patch=0
+    ;;
+  minor)
+    ((minor += 1))
+    patch=0
+    ;;
+  patch)
+    ((patch += 1))
+    ;;
+  *)
+    echo "Invalid version type: $type"
+    exit 1
+    ;;
+  esac
+
+  echo "$major.$minor.$patch"
+}
+
 ################################################################
 ################# Main script execution ########################
 ################################################################
 run_checks "$@"
 
 # Initialize variables
-VERSION=$1
+VERSION_TYPE=$1
+CURRENT_VERSION=$(get_current_version)
+NEW_VERSION=$(increment_version "$CURRENT_VERSION" "$VERSION_TYPE")
 THIS_SCRIPT=$(realpath "$0")
 SCRIPTS_DIR=$(dirname "$THIS_SCRIPT")
 ROOT_DIR=$(dirname "$SCRIPTS_DIR")
@@ -41,18 +79,18 @@ PYPROJECT_FILE="$META_DIR/pyproject.toml"
 BUILD_SCRIPT="$SCRIPTS_DIR/build.sh"
 
 # Update the version in pyproject.yaml
-sed -i "s/^version = \".*\"/version = \"$VERSION\"/" "$PYPROJECT_FILE"
+sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" "$PYPROJECT_FILE"
 
 # Commit the change
 git add pyproject.toml
-git commit -m "Update package version to $VERSION"
+git commit -m "Update package version to $NEW_VERSION"
 
 # Create a git tag
-git tag "v$VERSION"
+git tag "v$NEW_VERSION"
 
 # Push the commit and the tag
 git push origin main
-git push origin "v$VERSION"
+git push origin "v$NEW_VERSION"
 
 # Build the distribution files and push to PyPI
 sh "$BUILD_SCRIPT" --push-main
